# Generated by Django 4.0.3 on 2022-03-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nearbysearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('rad', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
