# Generated by Django 4.0.3 on 2022-03-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='types',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
