# Generated by Django 4.0.3 on 2022-03-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_place_addresscomponents'),
    ]

    operations = [
        migrations.AddField(
            model_name='nearbysearch',
            name='loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nearbysearch',
            name='rad',
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='nearbysearch',
            unique_together={('x', 'y', 'name', 'rad')},
        ),
    ]
