# Generated by Django 4.0.3 on 2022-03-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nearbysearch_loaded_alter_nearbysearch_rad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='vicinity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
