# Generated by Django 4.0.3 on 2022-03-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_place_vicinity'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='isBusiness',
            field=models.BooleanField(default=False),
        ),
    ]
