# Generated by Django 4.0.3 on 2022-03-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_easypage_easylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='easylist',
            name='pages',
            field=models.ManyToManyField(blank=True, to='core.easypage'),
        ),
    ]
