# Generated by Django 4.0.3 on 2022-03-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_easylist_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='EasyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('c', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='easylist',
            name='url',
        ),
        migrations.AddField(
            model_name='easylist',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='easylist',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='easylist',
            name='rad',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='easylist',
            name='categories',
            field=models.ManyToManyField(blank=True, to='core.easycategory'),
        ),
    ]
