# Generated by Django 4.0.3 on 2022-03-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_easycategory_remove_easylist_url_easylist_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='easypage',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='easypage',
            name='bestsubcat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='easypage',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='easypage',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='easypage',
            name='page_id',
            field=models.CharField(default='Empty', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='easypage',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
