# Generated by Django 4.0.3 on 2022-03-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_easypage_address_easypage_bestsubcat_easypage_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='easypage',
            name='logo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
