# Generated by Django 4.0.3 on 2022-03-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_easypage_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='easypage',
            name='hasData',
            field=models.BooleanField(default=False),
        ),
    ]
