# Generated by Django 4.0.3 on 2022-03-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_easypage_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='easypage',
            name='infoBox',
            field=models.TextField(blank=True, null=True),
        ),
    ]
